/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppForms;
import Libs.Lot;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author espirituwong
 */
public class BuyLotForm extends javax.swing.JPanel {

//    private ArrayList<Lot> availableLots;
    
    /**
     * Creates new form BuyLotPanel
     */
    
    public BuyLotForm(ArrayList<Lot> availableLots) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // closes only current window

    }    
        
//    public BuyLotForm(ArrayList<Lot> availableLots) {
//      this.availableLots = availableLots;
//        initComponents();
//        populateLotsChoice();
//    }

//    private void populateLotsChoice() {
//        for (Lot lot : availableLots) {
//            choice1.add(lot.getLocation());
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_ReserveLot = new javax.swing.JButton();
        btn_BuyLot = new javax.swing.JButton();
        btn_ExitLot = new javax.swing.JButton();
        jtxt_Price = new javax.swing.JTextField();
        jtxt_Size = new javax.swing.JTextField();
        jtxt_Loc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Fira Code", 0, 20)); // NOI18N
        jLabel2.setText("Are you sure you want this lot?");

        btn_ReserveLot.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        btn_ReserveLot.setText("Reserve Lot");
        btn_ReserveLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReserveLotActionPerformed(evt);
            }
        });

        btn_BuyLot.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        btn_BuyLot.setText("Buy lot");
        btn_BuyLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuyLotActionPerformed(evt);
            }
        });

        btn_ExitLot.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        btn_ExitLot.setText("No, exit");
        btn_ExitLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitLotActionPerformed(evt);
            }
        });

        jtxt_Price.setFont(new java.awt.Font("Fira Code", 2, 14)); // NOI18N
        jtxt_Price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Price.setText("lot price here");

        jtxt_Size.setFont(new java.awt.Font("Fira Code", 2, 14)); // NOI18N
        jtxt_Size.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Size.setText("lot size here");

        jtxt_Loc.setFont(new java.awt.Font("Fira Code", 2, 14)); // NOI18N
        jtxt_Loc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Loc.setText("lot loc here");

        jLabel4.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jLabel4.setText("Size");

        jLabel5.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jLabel5.setText("Location");

        jLabel6.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jLabel6.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_BuyLot, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_ReserveLot, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_ExitLot, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxt_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtxt_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BuyLot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ReserveLot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ExitLot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    // reserve lot btn
    private void btn_ReserveLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReserveLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ReserveLotActionPerformed

    // buy lot btn
    private void btn_BuyLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuyLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuyLotActionPerformed

    // exit btn
    private void btn_ExitLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitLotActionPerformed
        
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        
    }//GEN-LAST:event_btn_ExitLotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuyLot;
    private javax.swing.JButton btn_ExitLot;
    private javax.swing.JButton btn_ReserveLot;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtxt_Loc;
    private javax.swing.JTextField jtxt_Price;
    private javax.swing.JTextField jtxt_Size;
    // End of variables declaration//GEN-END:variables

    private void setDefaultCloseOperation(int DISPOSE_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
